### ISSUE TITLE
The survey is not displayed when the user exits the study

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [alastor0325/autoplay-shield-study#17]
**[Affected versions]:**
- Beta Unbranded 63.0b13 

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
	- extensions.legacy.enabled to true
	- xpinstall.signatures.required to false
	- extensions.fastblock_shield_mozilla_org.test.variationName to one of the following values: allow-and-remember.
	- xpinstall.signatures.required to false.
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Open the Firefox browser with the profile from the prerequisites.
2. Navigate to the "about:addons" page and click the "Remove" button from the "Block-autoplay" add-on. 
3. Observe the browser's tabs. 

**[Expected result]:**
- A new tab containing the "Block-autoplay" survey is opened.

**[Actual results]:**
- No new tabs are opened.
 
**[Notes]:** 
- This is a possible scenario a user can encounter when choosing to remove the shield study from the "about:studies" page.
- We used the scenario with an unsigned build and removed the add-on from "about:addons" as we cannot see the study in the "about:studies" page. 
- Attached a screen recording with the issue:

![rec of the issue - survey](https://user-images.githubusercontent.com/37875464/46812813-2da28880-cd7e-11e8-8338-240689c38a01.gif)

**Comment by alastor0325** [comment]
Do you use the signed extension for testing? You can find the signed verision in [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1475099). If you use that signed extension, you won't see that it appears in `about:config`, because it would be hidden in order to avoid user remove this extension from `about:addon`.

I will close this bug because this testing scenario is totally different with the scenario which user removes add-on from `about:config`.

Removing add-on from `about:config` is via `AddonManager`, and removing add-on from `about:studies` is via `Normandy Service`. These two ways has different uninstalling process, so you can't treat them as same thing. Also, even if we succeed on the one scenario, it doesn't mean we would succeed on another one, because they require different implementation.

As I [mentioned](
https://github.com/alastor0325/autoplay-shield-study/issues/10#issuecomment-424115871) before, the shield-study team doesn't provide any way for us in order to test whether the behaviors after uninstallation add-on are successful or not. I'm also wanting to test this part, but I'm sorry we don't have any method now.
