### ISSUE TITLE
The "Block-autoplay" shield study is not removed when the "Disable" button is clicked

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [alastor0325/autoplay-shield-study#9]
**[Affected versions]:**
- Firefox Beta Unbranded 63.0b8

**[Affected Platforms]:** 	 	
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have the following prefs:
      - shieldStudy.logLevel to All
      - extensions.fastblock_shield_mozilla_org.test.variationName to one of the following values: control, block, allow-and-remember or allow-and-notRemember
      - extensions.legacy.enabled to true
      - xpinstall.signatures.required to false 
- The Block-autoplay add-on is installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Navigate to "about:addons>Extensions" and click the "Block-autoplay" add-on.
3. Click the "Disable" button and observe the behavior.

**[Expected result]:**
- The "Block-autoplay" shield study is removed and there is no "Undo" option.

**[Actual result]:**
- The "Block-autoplay" shield study is disabled.

**[Notes]:**
- After the study is re-enabled, the "install" and "enter" pings are sent again.
- Added a screen recording the issue:

![disable](https://user-images.githubusercontent.com/40061643/45961284-cc14b700-c026-11e8-878f-176345502dbb.gif)

**Comment by alastor0325** [comment]
@Softvision-RemusDranca In fact, the shield-study extension would only show in `about:studies` , instead of in `about:addon`. The reason you can see this extension in `about:addon` is because this extension has not been signed and deployed by offical extension process. This extension is still in testing. 

Therefore, you can not disable or remove this extension in `about:addon` in real situation, I will close this bug.
